version: "3.9"
services:
    api:
        build: api/.
        ports:
            - "8088:8080"
        volumes:
            - ./logs:/app/logs
            - texinputs:/app/texinputs
            - pdfs:/app/pdfs
    latex:
        build: latex/.
        ports:
            - "8050:8081"
        volumes:
            - ./logs:/app/logs
            - texinputs:/app/texinputs
            - pdfs:/app/pdfs
volumes:
    texinputs: {}
    pdfs: {}